### PR TITLE
Add better GPU support

### PR DESCRIPTION
**Pull request by zdk123**
Implements the bugs I raised in #4 and #5.

Hope you take and accept PRs! Thanks

### CODE REVIEW

**Review by teevee112 — APPROVED** [review]
Good Catch! Thanks for the fix.

**Comment by DrLeucine** [comment]
@zdk123 which python version did you use?

**Comment by zdk123** [comment]
3.9

**Comment by DrLeucine** [comment]
Do you have instructions on how to install? After the upgrade I can’t seem to run off GPU :/

**Pull request merged**
